version: '3.9'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: siem
      POSTGRES_PASSWORD: siem
      POSTGRES_DB: siem
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: postgresql://siem:siem@db:5432/siem
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  pgdata:
